### ISSUE TITLE
Error: Unknown host type: Group

### ISSUE THREAD

**Issue by bucinskasj** [francescov1/facebook-event-scraper#11]
Hi Francesco,

Some links error out, because events are organized by a group. They are still publicly accessible, though. Here are some of the examples:

https://www.facebook.com/events/2495663160594046/
https://www.facebook.com/events/259083953672453/

Error in question:

Error: Unknown host type: Group
at /var/app/current/node_modules/facebook-event-scraper/dist/utils/htmlParser.js:107:19
at Array.map (<anonymous>)
at Object.getHosts (/var/app/current/node_modules/facebook-event-scraper/dist/utils/htmlParser.js:104:21)
at /var/app/current/node_modules/facebook-event-scraper/dist/scraper.js:53:30
at Generator.next (<anonymous>)
at fulfilled (/var/app/current/node_modules/facebook-event-scraper/dist/scraper.js:28:58)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by francescov1** [comment]
Hey @bucinskasj, nice catch, should be quick to add support!

**Comment by francescov1** [comment]
Fix is live in v0.0.11 🎉
